### ISSUE TITLE
Memory leak on TextPainter

### ISSUE THREAD

**Issue by tmpsantos** [leisim/auto_size_text#150]
Running the unit tests with [leak tracker](https://github.com/dart-lang/leak_tracker) enabled will fail because TextPainter is not being disposed. Fix on #149 

```
  Expected: leak free
    Actual: <Instance of 'Leaks'>
     Which: contains leaks:
            # The text is generated by leak_tracker.
            # For leak troubleshooting tips open:
            # https://github.com/dart-lang/leak_tracker/blob/main/doc/TROUBLESHOOT.md
            notDisposed:
              total: 140
              objects:
                TextPainter:
                  test: Group sync
                  identityHashCode: 360054994
                TextPainter:
                  test: Group sync
                  identityHashCode: 134151191
                TextPainter:
                  test: Group sync
                  identityHashCode: 490481355
                TextPainter:
                  test: Group sync
                  identityHashCode: 494110995
                TextPainter:
                  test: Group sync
                  identityHashCode: 664187944
                TextPainter:
                  test: Group sync
                  identityHashCode: 689149618
```
