### ISSUE TITLE
Would be nice to have a way to coordinate font autosizing across multiple widgets

### ISSUE THREAD

**Issue by dalewking** [leisim/auto_size_text#5]
I have a bunch of widgets where I would like to have the text be as large as possible but the font size needs to be the same for all the widgets.

Basically want a way to say that the widgets share an autosize controller and the font is set to the minimum font size across all the widgets.

**Comment by leisim** [comment]
Thanks for the idea. I'll implement this but it may take a few days ;)

**Comment by leisim** [comment]
@dalewking 

I have implemented the feature. It would be nice if you could test it before I release a new version. I hope it does what you wanted. If not just tell me what goes wrong.

You can add the test version by adding the following to your `pubspec.yaml`:

```yaml
dependencies:
  auto_size_text:
    git:
      url: git://https://github.com/leisim/auto_size_text.git
      ref: font-size-sync
```

Just give all `AutoSizeText`s you want to sync the same instance of `AutoSizeSyncGroup`.
```dart
var group = AutoSizeSyncGroup();

AutoSizeText(
  "Your Text",
  syncGroup: group,
);
```
